### PR TITLE
Created a `setup.py` for PIP Installation

### PR DESCRIPTION
**Pull request by nathanielvarona**
## Installation
```sh
export GITHUB_HANDLER = "<maintainer username>"
pip install git+https://github.com/${GITHUB_HANDLER}/pritunl-api-python.git@master#egg=pritunl-api
```

### CODE REVIEW

**Comment by nathanielvarona** [comment]
Repo has been inactive for many years. Closing the PR, I'll improve this package at my fork for now.

**Comment by nathanielvarona** [comment]
@ijat, let me know if you are still active in this project. I might frequently create a lot of changes and PRs in this project.

**Comment by ijat** [comment]
Hey, it's best for you to fork this repo cause I'm not active on this project anymore. I'll put a link in a description to your repo if you like.

**Comment by nathanielvarona** [comment]
Yes, please! That would be good, explicitly pointing to my fork.  
Then create a new status in your repo`Deprecation and Archive Notice`. 

Initially, I now have this release [Fork Release](https://github.com/nathanielvarona/pritunl-api-python/releases)
And a lot more improvements.
Thanks @ijat

**Pull request closed without merging**
